ERROR - 2022-10-26 12:19:35 --> mysqli_sql_exception: Table 'cash_book.user' doesn't exist in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\cashbook\app\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-10-26 12:19:35 --> Call to a member function getFirstRow() on bool
in SYSTEMPATH\Model.php on line 250.
 1 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 2 APPPATH\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
 3 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-10-26 12:20:26 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'bdcash_book' in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'bdcash_book', 3306, '', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\cashbook\app\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'bdcash_book' in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\cashbook\app\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
#7 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-10-26 12:20:26 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'bdcash_book'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-10-26 17:48:32 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'livro_caixa', 3306, '', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\cashbook\app\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\cashbook\app\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
#7 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-10-26 17:48:32 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(622): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(149): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Auth->loginUser()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-10-26 18:09:24 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-10-26 18:14:06 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-10-26 18:18:08 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-10-26 18:21:08 --> Undefined constant "console"
in APPPATH\Views\moviments\index.php on line 23.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('moviments/index', [], true)
 4 APPPATH\Controllers\Moviment.php(33): view('moviments/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Moviment->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-10-26 18:22:35 --> Undefined constant "console"
in APPPATH\Views\moviments\index.php on line 33.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('moviments/index', [], true)
 4 APPPATH\Controllers\Moviment.php(33): view('moviments/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Moviment->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-10-26 18:45:15 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-10-26 19:02:28 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-10-26 19:05:46 --> mysqli_sql_exception: Column 'description' cannot be null in C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO mov...', 0)
#1 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO mov...')
#2 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO mov...')
#3 C:\xampp\htdocs\cashbook\app\Controllers\Moviment.php(69): CodeIgniter\Database\BaseConnection->query('INSERT INTO mov...', Array)
#4 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Moviment->store()
#5 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Moviment))
#6 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cashbook\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cashbook\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}
